### ISSUE TITLE
Restore command crashed with TypeError

### ISSUE THREAD

**Issue by cpaucar3** [jleclanche/python-bna#17] opened 2018-11-12 17:59 UTC
Using latest commit 1e95483, see below:

chris@virtualBoxUbuntu:\~/python-bna$ echo $PYTHONPATH
/home/chris/.local/lib/python3.7/site-packages:
chris@virtualBoxUbuntu:\~/python-bna$ python3.7 --version
Python 3.7.1
chris@virtualBoxUbuntu:~/python-bna$ python3.7 ./bin/bna restore AA-1111-2222-3333 ABCDEFGHIJ
Traceback (most recent call last):
  File "./bin/bna", line 281, in <module>
    main()
  File "/home/chris/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/chris/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/chris/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chris/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chris/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/chris/.local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./bin/bna", line 229, in restore
    ctx.obj.add_serial(serial, secret, set_default=set_default)
  File "./bin/bna", line 89, in add_serial
    self.set_secret(serial, secret)
  File "./bin/bna", line 136, in set_secret
    self.config.set(serial, "secret", secret)
  File "/usr/lib/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

**Comment by jleclanche** [comment] 2019-10-11 22:31
Fixed duplicate of #18.

**Closed by jleclanche** 2019-10-11 22:31 UTC
